# Site settings
title: William Kurosawa
email: wkurosawa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  William Kurosawa - Developer, mainly Ruby, but also PHP,
  JavaScript and any other needed :-)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://williamkurosawa.com" # the base hostname & protocol for your site
twitter_username: toshibr
github_username:  wkurosawa

# Build settings
markdown: kramdown
